**Introduction to Python**<br>
By<br>
MD. SHARIFUL ISLAM SIFAT

In [7]:
print("Hello, World!")
print("I am learning Python.")
print("It is awesome!")

Hello, World!
I am learning Python.
It is awesome!


In [8]:
a = input("Enter value for a: ")
b = input("Enter value for b: ")

print("The number you have entered for a is ", a)
print("The number you have entered for b is ", b)

Enter value for a: 3
Enter value for b: 3
The number you have entered for a is  3
The number you have entered for b is  3


In [9]:
price = 100
qty = 5
total = price*qty
print ("Total = ", total)

Total =  500


In [10]:
print(3)
print(358)

3
358


In [11]:
print(3 + 3)
print(2 * 5)

6
10


In [12]:
print("I am", 35, "years old.")



I am 35 years old.


In [13]:
3 + 3

6

In [14]:
1>-4

True

In [15]:
-5>1

False

In [16]:
print(len("Sifat"))
print(len("Md Shariful Islam Sifat"))

5
23


In [17]:
"S" == "s"

False

In [18]:
5 == 6

False

In [19]:
x = 10
y = 5

x*y > 1

True

In [20]:
a = 1
b = 2
c = 3

d = a*b*c
print(d)

6


**Python Variables**


In [21]:
x = 5
y = "John"
print(x)
print(y)

5
John


In [22]:
x, y, z = "Orange", "Banana", "Cherry"
print(x)
print(y)
print(z)

Orange
Banana
Cherry


In [23]:
x = y = z = "Orange"
print(x)
print(y)
print(z)

Orange
Orange
Orange


In [24]:
fruits = ["apple", "banana", "cherry"]
x, y, z = fruits
print(x)
print(y)
print(z)

apple
banana
cherry


In [25]:
x = "Python"
y = "is"
z = "awesome"
print(x, y, z)
#print(x + y + z)


Python is awesome


In [26]:
x = 5
y = 10
print(x + y)
print(x - y)

15
-5


In [27]:
x = 5
y = "John"
print(x, y)
#print(x + y)

5 John


In [28]:
x = "awesome"

def myfunc():
  print("Python is " + x)

myfunc()

Python is awesome


**Python Data Types**


*   **str:** string, text
*   **int:** inetger numbers
*   **float:** real numbers, decimal values
*   **bool:** True, False

In [29]:
name = "Sifat"         # str
age = 25               # int
Weight = 66.300        # float
is_student = True      # bool

In [30]:
name = 'Salah'
print("name : ", name)

birth_year = 1987
print("birth_year : ", birth_year)

height = 5.6
print("height : ", height)

no_1_player = False
print("no_1_player : ", no_1_player)


name :  Salah
birth_year :  1987
height :  5.6
no_1_player :  False


**Mathematical operations**

In [31]:
a = 5 #integer
b = 6 #integer

# Addition
print("a+b = ", a+b)

# Multiplication
print("a*b = ", a*b)

# Subtraction
print("a-b = ", a-b)

# Modulus: Divides left hand operand by right hand operand and returns remainder
print("a%b = ", a%b)

# Division
print("a/b = ", a/b)

# Floor Division - The division of operands
# where the result is the quotient in which
# the digits after the decimal point are removed.
# But if one of the operands is negative, the result is floored,
# i.e., rounded away from zero (towards negative infinity)
print("a//b = ", a//b)

# Exponent: Performs exponential (power) calculation on operators
print("a**b = ", a**b)

a+b =  11
a*b =  30
a-b =  -1
a%b =  5
a/b =  0.8333333333333334
a//b =  0
a**b =  15625


**Comparison Operators**

In [32]:
a = -1
b = 1

print("a == b : ", a == b)
print("a != b : ", a != b)
print("a >= b : ", a >= b)
print("a <= b : ", a <= b)
print("a > b  : ", a > b)
print("a < b  : ", a < b)

a == b :  False
a != b :  True
a >= b :  False
a <= b :  True
a > b  :  False
a < b  :  True


**Manipulating List**

In [33]:
fam = ['Sifat', 1.40, 'Sagor', 1.56]
fam_ext= fam + ['me', 2.00]
print(fam)
print(fam_ext)
del fam[1]
print(fam)

['Sifat', 1.4, 'Sagor', 1.56]
['Sifat', 1.4, 'Sagor', 1.56, 'me', 2.0]
['Sifat', 'Sagor', 1.56]


In [34]:
x= ["a", "b", "c"]
y=x
y[1]= "Y"

print(y)

['a', 'Y', 'c']


**Function**

In [35]:
A = [1, 2, 3, 4, 5, 6]
print(A)
max(A)

[1, 2, 3, 4, 5, 6]


6

In [36]:
round(1.6845, 3)

1.685

In [37]:
# Create variables var1 and var2
var1 = [1, 2, 3, 4]
var2 = True

# Print out type of var1
print(type(var1))

# Print out length of var1
print(len(var1))

# Convert var2 to an integer: out2
out2 = int(var2)

<class 'list'>
4


In [38]:
# Create lists first and second
first = [11.25, 18.0, 20.0]
second = [10.75, 9.50]

# Paste together first and second: full
full = first + second

# Sort full in descending order: full_sorted
Sorted = sorted(full)
print(Sorted)

full_sorted = sorted(full, reverse=True )

# Print out full_sorted
print(full_sorted)

[9.5, 10.75, 11.25, 18.0, 20.0]
[20.0, 18.0, 11.25, 10.75, 9.5]


**Methods**

In [39]:
# string to experiment with: place
place = "poolhouse"

# Use upper() on place
place_up = place.upper()

# Print out place and place_up
print(place)
print(place_up)

# Print out the number of o's in place
print(place.count('o'))

poolhouse
POOLHOUSE
3


In [40]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Print out the index of the element 20.0
print(areas.index(20.0))

# Print out how often 9.50 appears in areas
print(areas.count(9.50))

2
1


In [41]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Use append twice to add poolhouse and garage size
areas.append(24.5)
areas.append(15.45)

# Print out areas
print(areas)

# Reverse the order of the elements in areas
areas.reverse()

# Print out areas
print(areas)

[11.25, 18.0, 20.0, 10.75, 9.5, 24.5, 15.45]
[15.45, 24.5, 9.5, 10.75, 20.0, 18.0, 11.25]


**Package**

In [42]:
# Import the math package
import math as ma

# Calculate C
C = 2 * 0.43 * ma.pi

# Calculate A
A = ma.pi * 0.43 ** 2

print("Circumference: " + str(C))
print("Area: " + str(A))

Circumference: 2.701769682087222
Area: 0.5808804816487527


In [43]:
# Import pi function of math package
from math import pi

# Calculate C
C = 2 * 0.43 * pi

# Calculate A
A = pi * 0.43 ** 2

print("Circumference: " + str(C))
print("Area: " + str(A))

Circumference: 2.701769682087222
Area: 0.5808804816487527


**NumPy** <br>
NumPy (Numerical Python) is a Python library used for fast numerical computations. It provides a powerful data structure called the NumPy array (ndarray), which is more efficient than Python lists for mathematical operations.






*   array[i] → One element.
*   array[start:end] → Elements from start to end-1.
*   array[:5] → First 5 elements.
*   array[5:] → From index 5 to the end.
*   array[-1] → Last element.



In [44]:
import pandas as pd
mlb = pd.read_csv("https://assets.datacamp.com/course/intro_to_python/baseball.csv")
height_in = mlb['Height'].tolist()  # Make sure to use this list

import numpy as np
# Create a numpy array from height_in
np_height_in = np.array(height_in)

# Print out np_height_in
print(np_height_in)

# Convert np_height_in to meters
np_height_m = np_height_in * 0.0254

# Print np_height_m
print(np_height_m)


[74 74 72 ... 75 75 73]
[1.8796 1.8796 1.8288 ... 1.905  1.905  1.8542]


In [45]:
import numpy as np

np_weight_lb = np.array([74, 74, 72, 75, 75, 73])
np_height_in = np.array([71, 72, 76, 72, 70, 72])

# Print out the weight at index 5
#np_weight_lb = np.array(np_weight_lb)
print(np_weight_lb[5])

# Print out sub-array of np_height_in: index 1 up to and including index 6
print(np_height_in[1:6])

73
[72 76 72 70 72]


**2D NumPy Array**

In [46]:
import numpy as np

baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

# Create a 2D numpy array from baseball
np_baseball = np.array(baseball)

# Print out the type of np_baseball
print(type(np_baseball))

# Print out the shape of np_baseball
print(np_baseball.shape)

<class 'numpy.ndarray'>
(4, 2)


In [47]:
import numpy as np

baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

# Create a 2D NumPy array
np_baseball = np.array(baseball)

# Print the first row (instead of the 50th row, since there are only 4 rows)
print("First row:")
print(np_baseball[0])

# Print the second row
print("\nSecond row:")
print(np_baseball[1])

# Select the entire second column (weights)
np_weight_lb = np_baseball[:, 1]

print("\nWeights:")
print(np_weight_lb)

# Print the height of the fourth player
print("\nHeight of the fourth player:")
print(np_baseball[3, 0])

First row:
[180.   78.4]

Second row:
[215.  102.7]

Weights:
[ 78.4 102.7  98.5  75.2]

Height of the fourth player:
188.0


In [48]:
import numpy as np

baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

updated = [[181, 79.4],
           [216, 103.7],
           [211, 99.5],
           [189, 76.2]]

# Create NumPy array
np_baseball = np.array(baseball)

# Print out addition of np_baseball and updated
print(np_baseball + updated)

# Create numpy array: conversion
conversion = np.array([0.0254, 0.453592])

# Print out product of np_baseball and conversion
print(np_baseball * conversion)

[[361.  157.8]
 [431.  206.4]
 [421.  198. ]
 [377.  151.4]]
[[ 4.572     35.5616128]
 [ 5.461     46.5838984]
 [ 5.334     44.678812 ]
 [ 4.7752    34.1101184]]


In [49]:
import numpy as np

# Sample baseball dataset
# [Height (inches), Weight (pounds)]
baseball = [
    [74, 180],
    [72, 215],
    [75, 210],
    [73, 188],
    [76, 220],
    [71, 175]
]

# Convert list to NumPy array
np_baseball = np.array(baseball)

# Select the first column (heights)
np_height_in = np_baseball[:, 0]

# Print the heights
print("Heights (inches):")
print(np_height_in)

# Calculate the mean
print("\nMean Height:")
print(np.mean(np_height_in))

# Calculate the median
print("\nMedian Height:")
print(np.median(np_height_in))

Heights (inches):
[74 72 75 73 76 71]

Mean Height:
73.5

Median Height:
73.5




*   np_baseball[:, 0] → Selects all rows of the first column (heights).
*   np.mean(np_height_in) → Calculates the average height.
*   np.median(np_height_in) → Calculates the median height



In [50]:
import numpy as np

# Height (inches), Weight (pounds)
baseball = [
    [74, 180],
    [72, 215],
    [75, 210],
    [73, 188],
    [76, 220],
    [71, 175]
]

np_baseball = np.array(baseball)

avg = np.mean(np_baseball[:, 0])
print("Average:", avg)

med = np.median(np_baseball[:, 0])
print("Median:", med)

stddev = np.std(np_baseball[:, 0])
print("Standard Deviation:", stddev)

corr = np.corrcoef(np_baseball[:, 0], np_baseball[:, 1])
print("Correlation Matrix:\n", corr)3

Average: 73.5
Median: 73.5
Standard Deviation: 1.707825127659933
Correlation Matrix:
 [[1.         0.55831789]
 [0.55831789 1.        ]]
